//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tako.Modbus.Client
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class ModbusClientAdpater
    {
        public virtual AbsModbusClient ModbusClient
        {
            get;
            set;
        }

        public virtual AbsModbusClient CreateModbusClient(EnumModbusFraming EnumModbusFrame)
        {
            switch (EnumModbusFrame)
            {
                case EnumModbusFraming.TCP:
                    this.ModbusClient = new TcpModbusClient();
                    break;

                case EnumModbusFraming.RTU:
                    this.ModbusClient = new RtuModbusClient();
                    break;

                case EnumModbusFraming.ASCII:
                    this.ModbusClient = new AsciiModbusClient();
                    break;

                default:
                    throw new ArgumentOutOfRangeException("EnumModbusFrame");
            }

            return this.ModbusClient;
        }
    }
}