//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tako.Modbus
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public enum EnumModbusFraming : byte
    {
        TCP = 0,
        RTU = 1,
        ASCII = 2,
    }
}