//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using System.IO.Ports;

namespace Tako.Modbus.Client
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Threading;

    public class AsciiModbusClient : RtuModbusClient
    {
        private AbsModbusRequest _modbusRequest = new AsciiModbusRequest();
        private AbsModbusResponse _modbusResponse = new AsciiModbusResponse();
        private AbsModbusDataConvert _modbusDataConvert = new AsciiModbusDataConvert();

        internal override AbsModbusRequest ModbusRequest
        {
            get { return _modbusRequest; }
            set { _modbusRequest = value; }
        }

        internal override AbsModbusResponse ModbusResponse
        {
            get { return _modbusResponse; }
            set { _modbusResponse = value; }
        }

        internal override AbsModbusDataConvert ModbusDataConvert
        {
            get { return _modbusDataConvert; }
            set { _modbusDataConvert = value; }
        }
    }
}